---
- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart qortex
  become: true
  ansible.builtin.systemd:
    name: qortex
    state: restarted
    enabled: true
